### ISSUE TITLE
Getting CORS error when using R2 storage

### ISSUE THREAD

**Issue by pvieira84** [oss-apps/split-pro#99]
Running into a CORS error when trying to upload a file as an attachment. Any hints on how to solve it? Self hosting with docker compose
<img width="472" alt="image" src="https://github.com/user-attachments/assets/6833ca0a-81c8-4967-b23a-cadb6b89cea0">

**Comment by KMKoushik** [comment]
It's cuz of this https://github.com/oss-apps/split-pro/blob/main/next.config.js#L35, need to add R2_PUBLIC url dynamically

**Comment by idoodler** [comment]
So there is no way to use a R2 Storage without modifying the code?

**Comment by KMKoushik** [comment]
I'll release a new version that fixes it

**Comment by KMKoushik** [comment]
oops sorry, you should also add this to cors policy in r2 bucket settings.

<img width="1110" alt="Screenshot 2024-09-28 at 6 52 33 am" src="https://github.com/user-attachments/assets/9ff2e378-dc23-44fc-9580-d794ebbc83e9">

**Comment by KMKoushik** [comment]
Released in 1.2.25

**Comment by KMKoushik** [comment]
oops that's my bad fixed in v1.2.26

**Comment by idoodler** [comment]
@KMKoushik Hm, there is something fishy, I am getting a code `400`.

Bucket configuration:
Access Policy: Tried `public` and `private`
                                                                                                                                                                                                                                                                                                     Access Key Policy: 
```
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Action": [
    "s3:PutObject",
    "s3:GetObject"
   ],
   "Resource": [
    "arn:aws:s3:::splitpro/*"
   ]
  },
  {
   "Effect": "Allow",
   "Action": [
    "s3:ListBucket"
   ],
   "Resource": [
    "arn:aws:s3:::splitpro"
   ]
  }
 ]
}
```

**Comment by KMKoushik** [comment]
@idoodler this is what i'm currently using. Can you try this and lemme know

```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::splitpro"
            ]
        },
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::splitpro/*"
            ]
        }
    ]
}
```

**Comment by KMKoushik** [comment]
btw, lemme know if you like receive updates on splitpro. more context: https://github.com/oss-apps/split-pro/discussions/93

**Comment by idoodler** [comment]
@KMKoushik no, its not working, letme try today with an Amazon S3 setup. 

I still get 400 back

**Comment by KMKoushik** [comment]
yes, please lemme know, i tried with r2 and minio and everything seems to work. it will be really helpful if you can send more logs from console, what's the error message for 400 etc. 

thank you for being patient and trying this out!

**Comment by pvieira84** [comment]
I am also getting HTTP 400. Img is uploaded correctly and I can see it in the bucket but then it is not displayed in split.pro
<img width="954" alt="image" src="https://github.com/user-attachments/assets/9bca34f5-8a29-444c-87a6-67f9e92628a4">

**Comment by KMKoushik** [comment]
@pvieira84 sorry for late reply, can you able to access the image directly with cloudlfare url? i tested it and seems to work!

**Comment by pvieira84** [comment]
@KMKoushik if I login to my cloudflare R2 dashboard, the file is there but it seems there is some issue preventing it from being displayed in SplitPro.

Can you let me know if my config below is correct:
<img width="568" alt="image" src="https://github.com/user-attachments/assets/7f7e0de1-a13c-45d9-b4a2-8b511295d610">

**Comment by KMKoushik** [comment]
@pvieira84 think that's the issue, you should enable public access and give the url of it!

<img width="1386" alt="Screenshot 2024-10-17 at 8 22 58 pm" src="https://github.com/user-attachments/assets/7367045e-c37b-482f-b24e-3907b860146e">

**Comment by KMKoushik** [comment]
it will be under your bucket settings

**Comment by pvieira84** [comment]
Thanks, I've done so:
<img width="970" alt="image" src="https://github.com/user-attachments/assets/16b674f9-2aaa-47ec-9729-fa8eea496934">

Now I can access the file with the URL from R2:
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/0688d49b-5425-42b4-861d-9a02f9793a73">


However, I can't access the file with the URL from splitpro:
<img width="770" alt="image" src="https://github.com/user-attachments/assets/d497ecbb-8692-4d74-a2a9-04533faed3a6">

**Comment by KMKoushik** [comment]
@pvieira84 can you get some logs from server?

**Comment by pvieira84** [comment]
@KMKoushik fixed - adding the "https://" prefix to the public R2 address did the trick for me

**Comment by KMKoushik** [comment]
glad it's working for you!
